### ISSUE TITLE
get_devices.py results in libdyson.exceptions.DysonInvalidAuth

### ISSUE THREAD

**Issue by dylanmcdermott** [shenxn/libdyson#15] opened 2021-09-11 22:27 UTC
Trying to get the credentials and getting this exception.

**Comment by nomis52** [comment] 2021-09-12 02:24
I found that you need to sign out from the dyson app. Once you do that, it asks for a passport and then emails the verification code.

**Comment by christianfus** [comment] 2021-09-24 10:15
Same problem here, logging out from the app didn't help.

**Comment by christianfus** [comment] 2021-09-24 11:00
After reseting the machine and linking it to new mail account, now it retrieves the devices.

**Comment by FireHelmet** [comment] 2021-11-20 18:09
Hello,

I got the same issue as you I guess,

`Traceback (most recent call last):
  File "C:\Users\User\Downloads\libdyson-0.8.8\get_devices.py", line 22, in <module>
    verify = account.login_email_otp(email, region)
  File "C:\Users\User\Downloads\libdyson-0.8.8\libdyson\cloud\account.py", line 127, in login_email_otp
    response = self.request(
  File "C:\Users\User\Downloads\libdyson-0.8.8\libdyson\cloud\account.py", line 119, in request
    raise DysonInvalidAuth
libdyson.exceptions.DysonInvalidAuth`

@christianfus what's machine did you reset ? could you give me more detail?

Thank you !

**Comment by christianfus** [comment] 2021-11-20 18:34
I was trying to make it work with a Dyson Pure Cool, I reset the machine and then link it to a new account with the Dyson app. But that was the temporal solution, the final solution is to connect it via mqtt connection.

**Comment by Kakise** [comment] 2021-11-24 11:22
Thanks @FireHelmet for pinging me here, so I figured out on another issue that this can be resolved by trying to disconnect your phone from Dyson Link right before running the get_devices script for some reason. It can take a few tries too, the auth flow is not consistent right now.

**Comment by FireHelmet** [comment] 2021-11-24 11:25
@Kakise , thanks I will try, I keep you informed !

**Comment by FireHelmet** [comment] 2021-11-24 12:07
@Kakise , I tried twice and I got this error below:

<img width="621" alt="R5O0anTU6I" src="https://user-images.githubusercontent.com/17533298/143235514-7e05d569-85d0-465c-aa93-b2871cc6f3bb.png">

Could you help ?

I will also try more times...

Thank you !

**Comment by FireHelmet** [comment] 2021-12-02 18:36
@Kakise I tried multiple times in different days, by signing out or not from Dyson mobile app and the issue persist. Could take a look in the code ?

Thank you !

**Comment by mjmcg** [comment] 2021-12-03 20:30
@

> 

I'm getting the same issue...I used Dyson Cloud to add my Dyson Pure Hot+Cool to Dyson Local. It stopped working so I deleted it from Dyson Local and tried to setup Dyson Cloud to add it again. No luck. I'm getting the same error that FireHelmet posted. Any help would be most appreciated! This integration has been rock solid since I set it up.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/dyson_cloud/__init__.py", line 43, in async_setup_entry
    devices = await hass.async_add_executor_job(account.devices)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/libdyson/cloud/account.py", line 167, in devices
  File "/usr/local/lib/python3.9/site-packages/libdyson/cloud/account.py", line 113, in request
    auth=self._auth if auth else None,
libdyson.exceptions.DysonInvalidAuth

**Comment by BenAChilds** [comment] 2022-01-29 05:47
Dropping in to say that the logging out from the app worked for me to at least allow me to finish Dyson Cloud HASS integration setup, but once that was complete I was given another log and the integration was inoperable.
Log entry:

```
2022-01-29 16:42:12 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <email>@gmail.com (AU) for dyson_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/dyson_cloud/__init__.py", line 43, in async_setup_entry
    devices = await hass.async_add_executor_job(account.devices)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/libdyson/cloud/account.py", line 167, in devices
    response = self.request("GET", API_PATH_DEVICES)
  File "/usr/local/lib/python3.9/site-packages/libdyson/cloud/account.py", line 113, in request
    raise DysonInvalidAuth
libdyson.exceptions.DysonInvalidAuth
```

**Comment by Fulg** [comment] 2022-02-09 19:01
On my end just launching the companion app on my phone (with it connected to my Dyson fan) was enough to fix this, no need to log out or reset anything. Then getting the credentials works fine.

If it's been a while since I launched the Dyson app, then I get `DysonInvalidAuth` as initially reported.

**Comment by FireHelmet** [comment] 2022-02-14 22:10
I still have the issue. I tried 3 times with and without being connected in the companion app.
I already tried to create a new dyson account too.

any chance to get this fixed?

![74DFF600-6C85-4B17-980B-717629DBA89B](https://user-images.githubusercontent.com/17533298/153954941-bd1ae624-4786-4984-8762-4536b053bc4b.jpeg)


Thanks!

**Comment by gazzmundo** [comment] 2022-02-26 10:14
+1 to this same issue, failing after asking for password and successfully receiving verification code.

**Comment by cyberlu** [comment] 2022-03-07 13:47
+1 
Logged out of the app. Tried during login. Repeatet 10 times without success.
`Please choose your account region
1: Mainland China
2: Rest of the World
Region [1/2]: 2
Region code: CH
Email: xyz@xxxxx.com
Traceback (most recent call last):
  File "D:\libdyson-main\get_devices.py", line 22, in <module>
    verify = account.login_email_otp(email, region)
  File "D:\libdyson-main\libdyson\cloud\account.py", line 122, in login_email_otp
    response = self.request(
  File "D:\libdyson-main\libdyson\cloud\account.py", line 114, in request
    raise DysonInvalidAuth
libdyson.exceptions.DysonInvalidAuth`

**Comment by kastrom** [comment] 2022-04-02 00:17
+1

Still getting the `DysonInvalidAuth` error immediately after entering my email address (unlike some I don’t even reach the password or OTP fields). This happens whether I try to configure directly within HA or using command line on a Ubuntu instance running in Docker. I don’t have a Windows machine to try.

![IMG_0637](https://user-images.githubusercontent.com/15103016/161356194-dd237d30-0d81-4246-b8ce-51a326e7273a.jpeg)

Steps I’ve tried:
- Logging out of the Dyson app and website
- Removing the fan from my Dyson account, setting up a new account and re-registering the device
- Running a VPN to check my ISP wasn’t somehow blocking the connection (I’m running 5G broadband so this happens occasionally)

I’ve seen some people have had success by changing the user agent, is this still a viable workaround? Any other suggestions?

**Comment by Ulrar** [comment] 2022-04-06 19:06
Same issue here, I get that exception as soon as I enter my email, no password.
I don't even have the app installed anymore so I can't log out.

**Comment by Kakise** [comment] 2022-04-08 18:17
I updated libdyson to v0.8.11, only change I made is changing the user agent used to connect to the api. It should fix further connection problems.

> Same issue here, I get that exception as soon as I enter my email, no password.
> I don't even have the app installed anymore so I can't log out, I've been using the dyson local integration for so long but it's been acting weird lately so I wanted to re-set it up

Please reinstall the app, login to your account and then log out, I was able to reproduce your issue by uninstalling the app before logout

**Closed by Kakise** 2022-04-08 18:17 UTC

**Comment by Ulrar** [comment] 2022-04-08 18:33
That does solve it, thanks !

**Comment by kastrom** [comment] 2022-04-10 10:05
I’m still getting the same error…

I’ve updated `ha-dyson` to v0.16.4-4, `ha-dyson-cloud` to v0.14.0 and Home Assistant core to 2022.4.1, and I’ve logged into and out of the Dyson app multiple times.

Is there something I’m missing? 🤔

```This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/dyson_cloud/config_flow.py:71 
Integration: Dyson Cloud (documentation, issues) 
First occurred: 10:45:30 (6 occurrences) 
Last logged: 10:57:30

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 206, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/dyson_cloud/config_flow.py", line 71, in async_step_email
    self._verify = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/libdyson/cloud/account.py", line 122, in login_email_otp
    response = self.request(
  File "/usr/local/lib/python3.9/site-packages/libdyson/cloud/account.py", line 114, in request
    raise DysonInvalidAuth
libdyson.exceptions.DysonInvalidAuth

```

**Comment by FireHelmet** [comment] 2022-04-10 12:31
@kastrom , yes you missed to use libdyson with Dyson Local component. Please re-read https://github.com/shenxn/ha-dyson/#setup-manually

When your credential is generated with libdyson, you need to use it in Dyson Local component from HA.
Don’t use Dyson cloud in this setup

**Comment by kastrom** [comment] 2022-04-10 17:50
Ah yes, I’d missed that this time around.

But after deleting and re-cloning `libdyson` (and logging in and out of the Dyson app) I’m still getting a `DysonInvalidAuth` failure:

![IMG_0639](https://user-images.githubusercontent.com/15103016/162632544-145d1bf1-9e97-4a9c-a901-fc87e653e349.jpeg)

**Comment by FireHelmet** [comment] 2022-04-11 11:07
@kastrom 

Retry after waiting more time between the logout from Dyson app and the login into libdyson.

I had same issue the first time and after it has worked

**Comment by kastrom** [comment] 2022-04-12 23:22
@FireHelmet thank you, you're a genius — I’d all but given up at this point.

And also thanks to @Kakise for the fix.
